name: terraform-cd

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-cd:
    uses: mmccarthy404/reusable-workflows/.github/workflows/terraform-cd.yaml@v1.0.0
    with:
      terraform-version: 1.5.0
      terraform-directory: .
      terraform-var-file: terraform.tfvars
      terraform-backend-config: backend.tfvars
      aws-region: us-east-1
      aws-role: arn:aws:iam::004351562122:role/github-oidc-terraform-remote-state
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}